export const API_ENDPOINTS = {
    LOGIN: '/login',
    REGISTER: '/register',
    LOGOUT: '/logout',
    APPROVED_DISPATCH: '/approved-dispatches',
    PASSENGER_COUNT: '/passenger-count',
    IN_QUEUE: '/in-queue',
    USERS_TOKEN : '/users/token',
    USER_PROFILE : '/users/profile',
    CHECK_USER_STATUS :'/check-user-status',
    RESERVE_SEAT: '/dispatches/ride',
    DISPLAY_SEATS: '/dispatch/reserved-seats',
    DISPLAY_APPROVED_SEATS: '/dispatch/approved-seats',
    DISPLAY_TICKET:'/approved-tickets',
    DISPLAY_RECEIPT:'/transaction/receipt',
    DISPLAY_TRANSACTION_AMOUNT:'/transaction/ticket/{id}',
    DISPLAY_QUANTITY_AMOUNT: '/ticket/price/{id}',
    PAY_SEATS: '/transaction/reserve',
    SHOW_EWALLET: '/e-wallets',
    REGISTER_EWALLET: '/e-wallet/register',
    PAY_SEATS_QR: '/transaction/reserveqr',
    DISPLAY_APPROVED_DISPATCH_BY_ID: '/approved-dispatches/{id}',
    DISPLAY_TRANSACTIONS_PER_USER: '/transaction/user',
    DISPLAY_CANCELLED_TICKETS_PER_USER: '/tickets/cancelled',
    DISPLAY_TRAVEL_HISTORY_PER_PASSENGER: '/travel-history/user',
    DISPLAY_USER_DETAILS: '/user/show',
    UPDATE_USER_DETAILS: '/user/update',
    UPDATE_USER_PROFILE_PIC: '/users/upload-profile',
    SENDING_EMAIL_VERIFICATION: '/authenticated/send-otp',
    VERIFY_EMAIL_OTP: '/authenticated/verify-otp',
    CHANGE_PASSWORD:'/user/update-password',
    SEND_OTP_PASSWORD_RESET:'/password-reset/send-otp',
    VERIFY_OTP_CHANGE_PASSWORD:'/password-reset/verify',
    FETCH_TRICYCLE_NUMBER:'/driver/tricycle-number',
    ADD_TRICYCLE_NUMBER:'/drivers/tricycle-number',
    UPDATE_TRICYCLE_NUMBER:'/driver/tricycle-number/update',

}
