export const API_ENDPOINTS = {
    LOGIN: '/login',
    REGISTER: '/register',
    LOGOUT: '/logout',
    APPROVED_DISPATCH: '/approved-dispatches',
    PASSENGER_COUNT: '/passenger-count',
    IN_QUEUE: '/in-queue',
    USERS_TOKEN : '/users/token',
    USER_PROFILE : '/users/profile',
    CHECK_USER_STATUS :'/check-user-status',
    RESERVE_SEAT: '/dispatches/ride',
    DISPLAY_SEATS: '/dispatch/reserved-seats',
    DISPLAY_APPROVED_SEATS: '/dispatch/approved-seats',
    DISPLAY_TICKET:'/approved-tickets',
    DISPLAY_RECEIPT:'/transaction/receipt',
    DISPLAY_TRANSACTION_AMOUNT:'/transaction/ticket/{id}',
    DISPLAY_QUANTITY_AMOUNT: '/ticket/price/{id}',
    PAY_SEATS: '/transaction/reserve',
    SHOW_EWALLET: '/e-wallets',
    REGISTER_EWALLET: '/e-wallet/register',
    PAY_SEATS_QR: '/transaction/reserveqr',
    DISPLAY_APPROVED_DISPATCH_BY_ID: '/approved-dispatches/{id}',

}
